/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'spmega' at '5/17/17 6:21 PM' with Gradle 2.14
 *
 * @author spmega, @date 5/17/17 6:21 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
